/**
 * Generate `supabase/seed/plans.sql` from the reviewed plan JSON files.
 * Depends on:
 *   - collage(collage_id,collage_na)    ← we insert 'IT'
 *   - department(department_id,...)     ← we insert 'CS'
 *   - major/plan/course/course_prereq   ← populated from JSON
 */
import fs from "node:fs";
import path from "node:path";
import type { ParsedPlan } from "./parse";

const outDir = path.join(__dirname, "out");
const seedFile = path.join(__dirname, "..", "..", "supabase", "seed", "plans.sql");

const files = fs.readdirSync(outDir).filter((f) => f.endsWith(".json") && !f.includes("tables"));
const plans: ParsedPlan[] = files.map((f) => JSON.parse(fs.readFileSync(path.join(outDir, f), "utf8")));

function sqlStr(v: string | null | undefined): string {
  if (v == null) return "null";
  return `'${v.replace(/'/g, "''")}'`;
}
function sqlNum(v: number | null | undefined): string {
  return v == null || !Number.isFinite(v) ? "null" : String(v);
}

const lines: string[] = [];
lines.push(`-- Generated by scripts/parse-plans/emit-sql.ts`);
lines.push(`-- DO NOT edit directly — re-run the emitter after updating JSON.`);
lines.push(`-- Paste into Supabase SQL editor AFTER applying 0002_academic.sql.`);
lines.push("");
lines.push(`begin;`);
lines.push("");

// ── 1. College + department (hard-coded; all plans belong to IT faculty / CS dept)
lines.push(`-- College & department`);
lines.push(`insert into public.collage(collage_id, collage_na)`);
lines.push(`values ('IT','كلية العلوم وتكنولوجيا المعلومات')`);
lines.push(`on conflict (collage_id) do update set collage_na = excluded.collage_na;`);
lines.push("");
lines.push(`insert into public.department(department_id, department_na, collage_id)`);
lines.push(`values ('CS','قسم علوم الحاسوب وتكنولوجيا المعلومات','IT')`);
lines.push(`on conflict (department_id) do update set department_na = excluded.department_na;`);
lines.push("");

// ── 2. Majors (dedupe by major_id)
const majorMap = new Map<string, { name: string; totalCredits: number | null }>();
for (const p of plans) {
  const existing = majorMap.get(p.major_id);
  const total = p.total_credits ?? null;
  if (!existing) majorMap.set(p.major_id, { name: p.major_na, totalCredits: total });
  else if (!existing.totalCredits && total) existing.totalCredits = total;
}
lines.push(`-- Majors`);
for (const [id, m] of majorMap) {
  // Default 132 total credits if unknown (matches cybersecurity PDF header)
  const credits = m.totalCredits ?? 132;
  lines.push(`insert into public.major(major_id, major_na, credit_hours, department_id)`);
  lines.push(`values (${sqlStr(id)}, ${sqlStr(m.name)}, ${sqlNum(credits)}, 'CS')`);
  lines.push(`on conflict (major_id) do update set major_na = excluded.major_na, credit_hours = excluded.credit_hours;`);
  lines.push("");
}

// ── 3. Plans
lines.push(`-- Plans`);
for (const p of plans) {
  lines.push(`insert into public.plan(plan_id, major_id, name, version_year)`);
  lines.push(`values (${sqlStr(p.plan_id)}, ${sqlStr(p.major_id)}, ${sqlStr(`${p.major_na} — ${p.plan_id}`)}, null)`);
  lines.push(`on conflict (plan_id) do update set name = excluded.name, major_id = excluded.major_id;`);
  lines.push("");
}

// ── 4. Courses
//    NOTE: course_id is primary key, so if the SAME code appears in multiple
//    plans we upsert and overwrite with the LATEST plan_id we see. We also
//    build a plan↔course link via a side-table approach: since the ER diagram
//    puts plan_id directly on course, we accept that a course belongs to at
//    most one plan in our model. In practice each of these 10 plans is a
//    different major, so duplicates between plans are minor (general-ed courses).
const allCourses = new Map<
  string,
  { name: string; credits: number; type: string; major_id: string; plan_id: string }
>();
for (const p of plans) {
  for (const c of p.courses) {
    // First plan wins for general-ed courses (shared IDs) — subsequent plans skip.
    if (!allCourses.has(c.course_code)) {
      allCourses.set(c.course_code, {
        name: c.course_name || c.course_code,
        credits: c.credit_hours,
        type: c.type,
        major_id: p.major_id,
        plan_id: p.plan_id,
      });
    }
  }
}

lines.push(`-- Courses (${allCourses.size} distinct course codes across ${plans.length} plans)`);
for (const [code, c] of allCourses) {
  lines.push(
    `insert into public.course(course_id, course_na, credit_hours, type, major_id, plan_id, semester_order)` +
      ` values (${sqlStr(code)}, ${sqlStr(c.name)}, ${sqlNum(c.credits)}, ${sqlStr(c.type)}, ${sqlStr(c.major_id)}, ${sqlStr(c.plan_id)}, null)` +
      ` on conflict (course_id) do update set course_na = excluded.course_na, credit_hours = excluded.credit_hours, type = excluded.type;`
  );
}
lines.push("");

// ── 5. Prereqs (only within resolved codes to satisfy FK)
const knownCodes = new Set(allCourses.keys());
let prereqCount = 0;
const skipped: string[] = [];
lines.push(`-- Course prerequisites`);
for (const p of plans) {
  for (const c of p.courses) {
    for (const pr of c.prereqs) {
      if (!knownCodes.has(pr.code)) {
        skipped.push(`${c.course_code} → ${pr.code}`);
        continue;
      }
      lines.push(
        `insert into public.course_prereq(course_id, prereq_course_id)` +
          ` values (${sqlStr(c.course_code)}, ${sqlStr(pr.code)})` +
          ` on conflict do nothing;`
      );
      prereqCount++;
    }
  }
}
lines.push("");
lines.push(`commit;`);
lines.push("");
lines.push(`-- Stats: ${allCourses.size} courses, ${prereqCount} prereq edges${skipped.length ? `, ${skipped.length} skipped (unresolved FK)` : ""}`);
if (skipped.length) {
  lines.push(`-- Skipped prereqs (target code not in any parsed plan):`);
  for (const s of skipped) lines.push(`--   ${s}`);
}

fs.mkdirSync(path.dirname(seedFile), { recursive: true });
fs.writeFileSync(seedFile, lines.join("\n"), "utf8");
console.log(
  `Wrote ${seedFile}  (${allCourses.size} courses, ${prereqCount} prereqs${
    skipped.length ? `, ${skipped.length} skipped` : ""
  })`
);
